### ISSUE TITLE
Height not properly calculated in IE 11 if using font-size: inherit

### ISSUE THREAD

**Issue by cecton** [andreypopp/react-textarea-autosize#198]
## Demo 

https://codesandbox.io/s/20lwok4oor

## Browsers

Works correctly on Edge, Chrome, FireFox but not on IE.

## Problem Description

The textarea height is miscalculated, it uses the font-size of the document instead of the div element.

Relevant css:

```css
textarea {
  font-size: 13px;
}

.container {
  font-size: 24px;
}

.container > textarea {
  font-size: inherit;
  width: 100%;
  overflow: hidden;
  resize: none;
  border: 0;
  outline: 0;
  background-color: lightblue;
}
```
