### ISSUE TITLE
Initial height too big

### ISSUE THREAD

**Issue by David-Oglesby** [andreypopp/react-textarea-autosize#258]
Using the following code:
```
<TextareaAutosize 
    className='myclass'
     placeholder='Add to the discussion' 
     value={discussion}
     minRows={2}
     onChange={changeDiscussion}
/>
.myclass { 
  width: 100%;
  min-height: 5rem;
  overflow: hidden;
  padding: .4rem 1.1rem;
  font-size: 1.4rem;
  color: #000;
  line-height: 1.5;
  border: .1rem solid #d9d9d9;
  border-radius: .4rem;
  white-space: pre-wrap;
}
```

The initial height is being set to 448.989px, when it should be closer to 52px. If I type something into the textarea the height jumps back to the correct height. Or, if I set the default value to any value, the default height will be correct.

I'm not sure if this is a specific issue with my code or an error in the component.

Fix:
If I change the outer container display to flex and then in myclass replace width:100% with flex: 0 0 100%, the textarea displays correctly.

**Comment by burtek** [comment]
That's somewhat funny, as for me the iitial height is too small xD

```css
.input {
    border: 1px solid #A8B7C7;
    border-radius: 2px;
    background-color: #FFFFFF;
    padding: 6px 14px;
    width: 100%;
}
```
