### ISSUE TITLE
Wrong height using box-sizing: border-box.

### ISSUE THREAD

**Issue by Andreyco** [andreypopp/react-textarea-autosize#37]
```css
textarea {
    height: 32px;
    border: 1px solid #ccc;
    box-sizing: border-box;
}
```

Computed height equals to 34px. In this case, it should equal to 32px, since *box-sizing: border-box* is applied.
